.github/workflows/test.yml
entrypoint.sh

More bash 😅, and also am aware that the amount of API calls could be reduced.
But a large chunk of this script should be removed soon anyway.
Also added a test for it.
Took the UUID determination logic from [here](https://github.com/1Password/onepassword-operator/blob/b574e394ad649d2cbf6f61192f00a1918cef8df3/pkg/onepassword/uuid.go#L7).

Fix item and vault loading by name

---

README.md

Since service accounts are in beta, we will not be including the documentation for this feature in Github until the official release. Instead, this info will be found in the beta documents in our 1Password docs portal

Removing mention of service accounts from the readme documentation

---

entrypoint.sh

It seemed that although the comment mentioned that we will generate a 64-character string for the heredoc identifier, we were generating a 32-character string instead.
This PR fixes this.

Make openssl generate a 64-character string as mentioned in comment

---

entrypoint.sh

This PR brings two changes:
- Pass User-Agent Information to the 1Password CLI
- Update the 1Password CLI installed in the pipeline to the latest version

Pass User-Agent Information to the 1Password CLI

---

entrypoint.sh

Quote $ref to avoid word splitting

---

.github/workflows/test.yml
README.md
action.yml
entrypoint.sh

This PR brings 2 changes that ensure that the GitHub Action is backwards compatible:
- Append `http://` if the prefix is not provided in the `OP_CONNECT_HOST` (this is caused by the fact that `curl` [guesses the protocol if not provided](https://linux.die.net/man/1/curl), which we missed when switching to using the 1Password CLI as the backend of the action)
- Set the default of `export-env` to `true`, since that was the default behavior of the action until we added the possibility to export secrets as step's output.
Also, the documentation is adjusted to reflect these changes.

Ensure that the action is backwards-compatible

---

entrypoint.sh

`set-output` & `save-state` are now deprecated
resolves 1Password/load-secrets-action#27

Use environment file to manage output instead of `set-output`

---

entrypoint.sh

Reverts 1Password/load-secrets-action#29
It seems that the tests fail when using the new syntax. Reverting this for now and will further investigate how to adjust the syntax so that the tests work again.

Revert "Use environment file to manage output instead of `set-output`"

---

entrypoint.sh

Relates to #28.
This PR properly installs the CLI on MacOS runners without sudo privileges.

Enable installing the CLI on MacOS runners without sudo privileges

---

.github/workflows/test.yml

This PR adds the following improvements:
- Use `actions/checkout@v3` since `v2` uses Node 12, which is deprecated.
- Use job matrix to enhance the testing matrices we cover.
Previously we were having 7 tests: 3 for Connect on Linux, 3 for service accounts on Linux, 1 for service accounts on MacOS. Each test had its own job, which lead to a lot of duplicated code.
With matrices, we've managed to do the following:
- Reduce the number of jobs written in the YAML file from 7 to 3 main cases:
- Test with secrets provided as a step output.
- Test with secrets provided as exported environment variables.
- Test with secret references that have IDs.
- Increase the number of tests from 7 to 9. Each of the 3 main test cases now cover the following 3 scenarios:
- 2 tests for service account: one on …

Improve pipelines

---

README.md

This PR adds instructions on how to use the action with Service Accounts (currently in beta)

Add documentation related to Service Accounts (currently in beta)

---

entrypoint.sh

Key changes in this PR:
- Use the new syntax for setting a step's output since [the old one is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
- Automatically fetch the latest stable version of the CLI.
- Add additional architectures for Linux
- Make the action fail if the GitHub Action runner's operating system is not supported.
Resolves: #27

Improve the shell script

---

entrypoint.sh

It seems that we can't assume that images have `jq` built-in, therefore we will use `grep` which comes built-in with all UNIX systems.
Resolves: #50

Parse CLI version without jq

---

README.md

The code example in the README is currently broken because of the syntax used to print the string Secret: ahead of the output. YAML requires strings that include special characters like : to be [enclosed with quotes to print correctly as a string](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml). This MR fixes that.

Fix example snippet in README

---

.github/workflows/test.yml
dist/index.js
src/utils.test.ts
src/utils.ts

This code is no longer needed. Instead, we will enforce users to add the protocol themselves.

Remove protocol prepending

---

README.md
dist/index.js
package-lock.json
package.json

This PR prepares the release of Load Secrets - GitHub Action v2.0.0
Resolves #61 
- Users are now required to include the protocol (i.e. `http://` or `https://`) when providing the Connect server host URL.
- Upgrade from Node 16 to Node 20.
- Migrate the functionality of the action from Shell to Typescript (except installing the 1Password CLI)

Prepare release v2.0.0

---

.github/workflows/test.yml
README.md

Update the Security section of the README to point to the new method of bug bounty reporting for this repo.
Also fix the `docker compose` command since the deprecated alias (`docker-compose`) is no longer present.

Update bug bounty process

---

.github/workflows/lint.yml
.github/workflows/test.yml

This ensures that:
- `Acceptance tests` workflow is run on pull requests (including the ones from external contributors)
- `Lint` is run on `main` branch.
- Workflows are executed only once on pull requests
**Context:** It was noticed that the `Acceptance tests` workflow was not executed on #82 which made the review cycle take way longer and required extra effort to identify bugs and regressions.

Make workflow targets more specific

---

.github/workflows/lint.yml
CONTRIBUTING.md
package-lock.json
src/utils.test.ts

This add the ES lint and the code formatting check to the `Lint` workflow.
Resolves #84.
Relates #83.

Add lint to workflow

---

package-lock.json
package.json

In Oct 2023, [`@1password/front-end-style`](https://www.npmjs.com/package/@1password/front-end-style) has been rewritten into 3 smaller packages:
- [`@1password/eslint-config`](https://www.npmjs.com/package/@1password/eslint-config)
- [`@1password/prettier-config`](https://www.npmjs.com/package/@1password/prettier-config)
- [`@1password/stylelint-config`](https://www.npmjs.com/package/@1password/stylelint-config)
These 3 new packages have the same configurations as the previous package, with the benefits of being up-to-date and better organized. In the case of this GitHub Action, we only need the first two. The last one is dedicated to CSS stylling, which is not used in this action. Therefore, we will replace the deprecated `@1password/front-end-style` with the following packages:
- …

Switch to new lint packages

---

.github/workflows/lint.yml
.github/workflows/test.yml

In a previous PR (#87) we used `branch` syntax to trigger the pipeline when a push on `main` was made. This was a mistake and [`branches`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs) is the correct syntax that achieves this.

Fix workflow branch syntax

---

.github/workflows/ok-to-test.yml
.github/workflows/test-fork.yml
.github/workflows/test.yml

Currently an external contributor can't have the acceptance tests run on their PR because `pull_request` doesn't give access to the secrets needed for them.
Therefore, in this PR we create a new workflow that is identical to the one for existing acceptance tests, with the following differences:
- This workflow can be triggered with the command `/ok-to-test sha="<contributor's latest commit sha>"` by one of this repo's maintainers.
- After the acceptance tests finish, their result will be updated to the PR's list of checks.

Run acceptance tests on fork

---

.github/workflows/acceptance-test.yml
.github/workflows/test-fork.yml
.github/workflows/test.yml

In #97 it was missed to adjust the reusable workflow to pull changes from the forked commit. Instead, now we pull from base repository, which doesn't contain the external contributor's changes.
I've also improved the way we reference the reusable workflow to ensure we're using a trusted reusable workflow that won't change often.

Fix fork workflow

---

.github/workflows/test.yml
package-lock.json
package.json

This PR:
- Bumps `op-cli-installer` version to the latest which sets default cli version if not provided by the caller.
- Reverts acceptance-test to point to the `main` branch.

Bump op-cli-installer version

---

README.md
action.yml

As we anyway plan to release [v3](https://github.com/1Password/load-secrets-action/pull/110), I think this is a good opportunity to introduce this breaking change.
So, in `v3` of the action the `export-env` input will defaults to `false`.
This will help to mitigate the next security concern. As exporting secret as env variable in the job will make it available for all future steps including 3d party actions. If some malicious 3d party action is used it can get an access to the secret from env var.
Though, the risk is low, the safer way for the action would be to defaults to `false` and let the users explicitly set `export-env` input, if they want to export secrets as env variables.
This PR also updates readme to show reccomended example of using secrets as step outputs as well as …

Set `export-env` input to `false` by default

---

README.md

The missing « s » makes the action fail in the example, as the id is not the same.

DOCS - Fix typo in the example with step’s output
